baseURL = "ariliang.me"
languageCode = "zh-cn"
title = "Ari's home"
theme = "ezhil"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    mode = "auto"
    math = true


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

# Enable tags.
[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = false
    style = "monokai"
    tabWidth = 4
    noClasses = true
    hl_Lines = ""
    lineAnchors = ""
    anchorLineNos = false